<?php
/**
 * @file
 * Code for the GSB Feature Chute FPP feature.
 */

include_once 'gsb_feature_chute_fpp.features.inc';

/**
 * Implement hook_form_id_form_alter.
 *
 * @param $form
 * @param $form_state
 */
function gsb_feature_chute_fpp_form_fieldable_panels_panes_entity_edit_form_alter(&$form, $form_state) {
  if ($form['#bundle'] == 'chute') {
    $form['#attached']['js'][] = drupal_get_path('module', 'gsb_feature_chute_fpp') . '/js/gsb_feature_chute_fpp.js';
  }
}